/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroSuperintendenteRouteImport } from './routes/cadastro.superintendente'
import { Route as CadastroAnciaoRouteImport } from './routes/cadastro.anciao'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroSuperintendenteRoute = CadastroSuperintendenteRouteImport.update({
  id: '/cadastro/superintendente',
  path: '/cadastro/superintendente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAnciaoRoute = CadastroAnciaoRouteImport.update({
  id: '/cadastro/anciao',
  path: '/cadastro/anciao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/cadastro/anciao': typeof CadastroAnciaoRoute
  '/cadastro/superintendente': typeof CadastroSuperintendenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/cadastro/anciao': typeof CadastroAnciaoRoute
  '/cadastro/superintendente': typeof CadastroSuperintendenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/cadastro/anciao': typeof CadastroAnciaoRoute
  '/cadastro/superintendente': typeof CadastroSuperintendenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/cadastro/anciao'
    | '/cadastro/superintendente'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/cadastro/anciao' | '/cadastro/superintendente'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/cadastro/anciao'
    | '/cadastro/superintendente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroAnciaoRoute: typeof CadastroAnciaoRoute
  CadastroSuperintendenteRoute: typeof CadastroSuperintendenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/superintendente': {
      id: '/cadastro/superintendente'
      path: '/cadastro/superintendente'
      fullPath: '/cadastro/superintendente'
      preLoaderRoute: typeof CadastroSuperintendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/anciao': {
      id: '/cadastro/anciao'
      path: '/cadastro/anciao'
      fullPath: '/cadastro/anciao'
      preLoaderRoute: typeof CadastroAnciaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroAnciaoRoute: CadastroAnciaoRoute,
  CadastroSuperintendenteRoute: CadastroSuperintendenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
